version: '3'
services:
  database:
    image: postgres
    volumes:
      - postgresdb:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: "password"
    restart: always
  web:
    build: ./xpark_backend
    restart: always
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - database
  frontend:
    build: ./xparkFront
    depends_on:
      - web
volumes:
    postgresdb: